bwecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('paypal/', include('paypal.standard.ipn.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views
from .views import (
    CheckoutView, 
    products,
    HomeView,
    ItemDetailView,
    add_to_cart,
    OrderSummaryView,
    remove_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    FilterShirtView,
    FilterSportwearView,
    FilterOutwearView,
    LegalView,
    remove_single_item_from_cart,
    process_payment,
    payment_done,
    payment_cancelled
)
app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home-page'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product-page'),
    path('add-to-cart/<slug>', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/',RequestRefundView.as_view(), name='request-refund' ),
    path('process-payment/', process_payment, name='process-payment'),
    path('payment-done/', payment_done, name='payment-done'),
    path('payment-cancelled/', payment_cancelled, name='payment-cancelled'),
    path('filter-shirt-view/', FilterShirtView.as_view(), name='filter-shirt-view'),
    path('filter-sportwear-view/', FilterSportwearView.as_view(), name='filter-sportwear-view'),
    path('filter-outwear-view/', FilterOutwearView.as_view(), name='filter-outwear-view'),
    path('legal-advice/', LegalView.as_view(), name='legal-advice')
]

templates/cookielaw/banner.html
{% load i18n static %}
<script src="{% static 'cookielaw/js/cookielaw.js' %}"></script>
<div id="CookielawBanner">
<div class="cookie-content">
    <div class="cookie-text">
        {% trans 'This website uses cookies to make your experience better.' %}
    </div>
    <div class="cookie-buttons">
         <a class="btn-blue" href="{% url 'core:legal-advice' %}">{% trans "What are the cookies?" %}</a>
         <a class="btn-orange" href="javascript:Cookielaw.createCookielawCookie();">{% trans "Ok, understood" %}</a>
    </div>
    <div class="close-cookies"></div>
</div>
</div>

<script type="application/javascript">
$(document).ready(function () {
   $('.close-cookies').click(function () {
       $(this).parent().hide();
   });
});
</script>

templates/cookielaw/banner2.html
{% load i18n static %}
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.4.1/jquery.min.js"></script>
<script>
$(document).ready(function(){
  
  if (confirm("Press a button!")) {
    javascript:Cookielaw.createCookielawCookie();
  } else {
    txt = "You pressed Cancel!";
  }
  
});
</script>

templates/cookielaw/banner3.html
{% load i18n static %}
{% load i18n %}

<div id="CookielawBanner">
    <div class="container">
        <h6>{% trans "COOKIE_INFO_HEADER" %}</h6>
        <p>
            <a class="btn btn-primary pull-right" href="javascript:Cookielaw.createCookielawCookie();">{% trans "COOKIE_INFO_OK" %}</a>
            {% trans "COOKIE_INFO_PARA" %}
        </p>
    </div>
</div>

<script type="application/javascript">

var Cookielaw = {

createCookie: function (name, value, days) {
    var date = new Date(),
        expires = '';
    if (days) {
        date.setTime(date.getTime() + (days * 24 * 60 * 60 * 1000));
        expires = "; expires=" + date.toGMTString();
    } else {
        expires = "";
    }
    document.cookie = name + "=" + value + expires + "; path=/";
},

createCookielawCookie: function () {
    this.createCookie('cookielaw_accepted', '1', 10 * 365);

    if (typeof (window.jQuery) === 'function') {
        jQuery('#CookielawBanner').slideUp();
    } else {
        document.getElementById('CookielawBanner').style.display = 'none';
    }
}

};
</script>