bwecommerce/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('', include('core.urls', namespace='core')),
    path('paypal/', include('paypal.standard.ipn.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL,
                          document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

core/urls.py
from django.urls import path
from . import views
from .views import (
    CheckoutView, 
    products,
    HomeView,
    ItemDetailView,
    add_to_cart,
    OrderSummaryView,
    remove_from_cart,
    PaymentView,
    AddCouponView,
    RequestRefundView,
    FilterShirtView,
    FilterSportwearView,
    FilterOutwearView,
    LegalView,
    remove_single_item_from_cart,
    process_payment,
    payment_done,
    payment_cancelled
)
app_name = 'core'

urlpatterns = [
    path('', HomeView.as_view(), name='home-page'),
    path('checkout/', CheckoutView.as_view(), name='checkout'),
    path('order-summary/', OrderSummaryView.as_view(), name='order-summary'),
    path('product/<slug>/', ItemDetailView.as_view(), name='product-page'),
    path('add-to-cart/<slug>', add_to_cart, name='add-to-cart'),
    path('add-coupon/', AddCouponView.as_view(), name='add-coupon'),
    path('remove-from-cart/<slug>/', remove_from_cart, name='remove-from-cart'),
    path('remove-item-from-cart/<slug>/', remove_single_item_from_cart, name='remove-single-item-from-cart'),
    path('payment/<payment_option>/', PaymentView.as_view(), name='payment'),
    path('request-refund/',RequestRefundView.as_view(), name='request-refund' ),
    path('process-payment/', process_payment, name='process-payment'),
    path('payment-done/', payment_done, name='payment-done'),
    path('payment-cancelled/', payment_cancelled, name='payment-cancelled'),
    path('filter-shirt-view/', FilterShirtView.as_view(), name='filter-shirt-view'),
    path('filter-sportwear-view/', FilterSportwearView.as_view(), name='filter-sportwear-view'),
    path('filter-outwear-view/', FilterOutwearView.as_view(), name='filter-outwear-view'),
    path('legal-advice/', LegalView.as_view(), name='legal-advice')
]

core/models.py
from django.db.models.signals import post_save
from django.conf import settings
from django.db import models
from django.shortcuts import reverse
from django_countries.fields import CountryField

CATEGORY_CHOICES = (
    ('S', 'Shirt'),
    ('SW', 'Sport wear'),
    ('OW', 'Outwear')
)

LABEL_CHOICES = (
    ('p', 'primary'),
    ('s', 'secondary'),
    ('d', 'danger')
)

ADDRESS_CHOICES = (
    ('B', 'Billing'),
    ('S', 'Shipping'),
)

# Create your models here.
class UserProfile(models.Model):
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL, on_delete=models.CASCADE)
    stripe_customer_id = models.CharField(max_length=50, blank=True, null=True)
    one_click_purchasing = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

class Item(models.Model):
    title = models.CharField(max_length=100)
    price = models.FloatField()
    discount_price = models.FloatField(blank=True, null=True)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    label = models.CharField(choices=LABEL_CHOICES, max_length=1)
    slug = models.SlugField()
    description = models.TextField()
    image = models.ImageField(blank=True, null=True)

    def __str__(self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("core:product-page", kwargs={
            'slug': self.slug
        })
    def get_add_to_cart_url(self):
        return reverse("core:add-to-cart", kwargs={
            'slug': self.slug
        })
    def get_remove_from_cart_url(self):
        return reverse("core:remove-from-cart", kwargs={
            'slug': self.slug
            })

class OrderItem(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL, 
    on_delete=models.CASCADE)
    ordered = models.BooleanField(default=False)
    item = models.ForeignKey(Item, on_delete=models.CASCADE)
    quantity = models.IntegerField(default=1)

    def __str___(self):
        return f"{self.quantity} of {self.item.title}"
    
    def get_total_item_price(self):
        return self.quantity * self.item.price
    
    def get_total_discount_item_price(self):
        return self.quantity * self.item.discount_price
    
    def get_amount_saved(self):
        return self.get_total_item_price() - self.get_total_discount_item_price()

    def get_final_price(self):
        if self.item.discount_price:
            return self.get_total_discount_item_price()
        return self.get_total_item_price()
    
    def get_total_quantity(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.quantity
        return total

class Order(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    ref_code = models.CharField(max_length=20, blank=True, null=True)
    items = models.ManyToManyField(OrderItem)
    start_date = models.DateTimeField(auto_now_add=True)
    ordered_date = models.DateTimeField()                        
    ordered = models.BooleanField(default=False)
    shipping_address = models.ForeignKey(
        'Address', related_name='shipping_address', on_delete=models.SET_NULL, blank=True, null=True)
    billing_address = models.ForeignKey(
        'Address', related_name='billing_address', on_delete=models.SET_NULL, blank=True, null=True)
    payment = models.ForeignKey(
        'Payment', on_delete=models.SET_NULL, blank=True, null=True)

    coupon = models.ForeignKey(
         'Coupon', on_delete=models.SET_NULL, blank=True, null=True)
    being_delivered = models.BooleanField(default=False)
    received = models.BooleanField(default=False)
    refund_requested = models.BooleanField(default=False)
    refund_granted = models.BooleanField(default=False)

    '''
    1. Item added to cart
    2. Adding a billing billing address
    (Failed checkout)
    3. Payment
    (Preprocessing, processing, packaging, etc.)
    4. Being delivered
    5. Received
    6. Refunds
    '''

    def __str___(self):
        return self.title

    def get_total(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.get_final_price()
        if self.coupon:
            total -= self.coupon.amount
        return total
    
    def get_total_quantity(self):
        total = 0
        for order_item in self.items.all():
            total += order_item.quantity()
        return total

class Address(models.Model):
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                            on_delete=models.CASCADE)
    street_address = models.CharField(max_length=100)
    apartment_address = models.CharField(max_length=100)
    country = CountryField(multiple=False)
    zip = models.CharField(max_length=100)
    address_type = models.CharField(max_length=1, choices=ADDRESS_CHOICES)
    default = models.BooleanField(default=False)

    def __str__(self):
        return self.user.username

    class Meta:
        verbose_name_plural='Addresses'
        
class Payment(models.Model):
    stripe_charge_id = models.CharField(max_length=50)
    paypal_charge_id = models.CharField(max_length=50)
    user = models.ForeignKey(settings.AUTH_USER_MODEL,
                             on_delete=models.SET_NULL, blank=True, null=True)
    
    amount = models.FloatField()
    timestamp = models.DateTimeField(auto_now_add=True)

    # def __str__(self):
    #     return self.user.username

    

class Coupon(models.Model):
    code = models.CharField(max_length=15)
    amount = models.FloatField()

    def __str__(self):
        return self.code

class Refund(models.Model):
    order = models.ForeignKey(Order, on_delete=models.CASCADE)
    reason = models.TextField()
    accepted = models.BooleanField(default=False)
    email = models.EmailField(default=False)

    def __str__(self):
        return f"{self.pk}"

def userprofile_receiver(sender, instance, created, *args, **kwargs):
    if created:
        userprofile = UserProfile.objects.create(user=instance)

post_save.connect(userprofile_receiver, sender=settings.AUTH_USER_MODEL)

templates/filter-outwear-view.html
{% extends "base.html" %}
{% block content %}
  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Top Items:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
             <a class="nav-link" href="{% url 'core:filter-shirt-view' %}">Shirt</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:filter-sportwear-view' %}">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:filter-outwear-view' %}">Outwears</a>
            </li>

          </ul>
         
          <!-- Links -->

          <form class="form-inline" method='GET'>
            <div class="md-form my-0">
              <input 
              class="form-control mr-sm-2" 
              type="text" 
              placeholder="Search" 
              aria-label="Search"
              name='search_item'>
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->
       <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <!-- <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol> -->
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <i class="fas fa-sun"></i>
                <strong>Solstyce Closet</strong>
              </h1>

              <p>
                <strong>Get the best goods here!</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>We have it all for you!</strong>
              </p>

            <!--   <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a> -->
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->
   </div>
    <!--/.Slides-->

    <!--Controls-->
    <!-- <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a> -->
    <!--/.Controls-->

  </div>
  
    
  <!--Main layout-->
<!--Section: Products v.3-->

<section class="text-center mb-4">
    
    <div class="row wow fadeIn">
      {% for item in object_list %}
        {% if item in filter.qs %}
      <div class="col-lg-3 col-md-6 mb-4">

        <!--Card-->
        <div class="card">

          <!--Card image-->
          <div class="view overlay">
            <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" -->
            <img src="{{ item.image.url }}"class="card-img-top" > 
            
            <a href="{{ item.get_absolute_url }}">
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
          <!--Card image-->

          <!--Card content-->
          <div class="card-body text-center">
            <!--Category & Title-->
            <a href="" class="grey-text">
                <!-- <h1>{{ item.category }}</h1> -->
              <h5>{{ item.get_category_display }}</h5>
            </a>
            <h5>
                <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      {% if item.label == 'p' %}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">HOT</span>
                      {% elif item.label == 's' %}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">Top Seller!</span>
                      {% else %}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                      {% endif %}
                    </a>
                  </strong>
            </h5>

            <h4 class="font-weight-bold blue-text">
              <strong>$
                {% if item.discount_price %}
                {{ item.discount_price }}
                {% else %}
                {{ item.price }}
                {% endif %}
              </strong>
            </h4>

          </div>
          <!--Card content-->

        </div>
        <!--Card-->

      </div>
      {% endif %}
      {% endfor %}
    </div>
  </section>
  
  <!--Section: Products v.3-->
  <br>
     <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
         {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->
      {% endif %}
    </div>
    </main>
  {% endblock content%}

templates/filter-sportwear-view.html
{% extends "base.html" %}
{% block content %}
  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Top Items:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
             <a class="nav-link" href="{% url 'core:filter-shirt-view' %}">Shirt</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:filter-sportwear-view' %}">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:filter-outwear-view' %}">Outwears</a>
            </li>

          </ul>
         
          <!-- Links -->

          <form class="form-inline" method='GET'>
            <div class="md-form my-0">
              <input 
              class="form-control mr-sm-2" 
              type="text" 
              placeholder="Search" 
              aria-label="Search"
              name='search_item'>
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->
       <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <!-- <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol> -->
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <i class="fas fa-sun"></i>
                <strong>Solstyce Closet</strong>
              </h1>

              <p>
                <strong>Get the best goods here!</strong>
              </p>
              
              <p class="mb-4 d-none d-md-block">
                <strong>We have it all for you!</strong>
              </p>

            <!--   <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a> -->
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->
   </div>
    <!--/.Slides-->

    <!--Controls-->
    <!-- <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a> -->
    <!--/.Controls-->

  </div>
  
    
  <!--Main layout-->
<!--Section: Products v.3-->

<section class="text-center mb-4">
    
    <div class="row wow fadeIn">
      {% for item in object_list %}
        {% if item in filter.qs %}
      <div class="col-lg-3 col-md-6 mb-4">

        <!--Card-->
        <div class="card">

          <!--Card image-->
          <div class="view overlay">
            <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" -->
            <img src="{{ item.image.url }}"class="card-img-top" > 
            
            <a href="{{ item.get_absolute_url }}">
              <div class="mask rgba-white-slight"></div>
            </a>
          </div>
          <!--Card image-->

          <!--Card content-->
          <div class="card-body text-center">
            <!--Category & Title-->
            <a href="" class="grey-text">
                <!-- <h1>{{ item.category }}</h1> -->
              <h5>{{ item.get_category_display }}</h5>
            </a>
            <h5>
                <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      {% if item.label == 'p' %}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">HOT</span>
                      {% elif item.label == 's' %}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">Top Seller!</span>
                      {% else %}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                      {% endif %}
                    </a>
                  </strong>
            </h5>

            <h4 class="font-weight-bold blue-text">
              <strong>$
                {% if item.discount_price %}
                {{ item.discount_price }}
                {% else %}
                {{ item.price }}
                {% endif %}
              </strong>
            </h4>

          </div>
          <!--Card content-->

        </div>
        <!--Card-->

      </div>
      {% endif %}
      {% endfor %}
    </div>
  </section>
  
  <!--Section: Products v.3-->
  <br>
     <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
         {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->
      {% endif %}
    </div>
    </main>
  {% endblock content%}

templates/home-page.html
{% extends "base.html" %}
{% block content %}

  <!--Main layout-->
  <main>
    <div class="container">

      <!--Navbar-->
      <nav class="navbar navbar-expand-lg navbar-dark mdb-color lighten-3 mt-3 mb-5">

        <!-- Navbar brand -->
        <span class="navbar-brand">Top Items:</span>

        <!-- Collapse button -->
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#basicExampleNav"
          aria-controls="basicExampleNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>

        <!-- Collapsible content -->
        <div class="collapse navbar-collapse" id="basicExampleNav">

          <!-- Links -->
          
          <ul class="navbar-nav mr-auto">
            <li class="nav-item active">
              <a class="nav-link" href="/">All
                <span class="sr-only">(current)</span>
              </a>
            </li>
            <li class="nav-item">
             <a class="nav-link" href="{% url 'core:filter-shirt-view' %}">Shirt</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:filter-sportwear-view' %}">Sport wears</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{% url 'core:filter-outwear-view' %}">Outwears</a>
            </li>

          </ul>
         
          <!-- Links -->

          <form class="form-inline" method='GET'>
            <div class="md-form my-0">
              <input 
              class="form-control mr-sm-2" 
              type="text" 
              placeholder="Search" 
              aria-label="Search"
              name='search_item'>
            </div>
          </form>
        </div>
        <!-- Collapsible content -->

      </nav>
      <!--/.Navbar-->
       <!--Carousel Wrapper-->
  <div id="carousel-example-1z" class="carousel slide carousel-fade pt-4" data-ride="carousel">

    <!--Indicators-->
    <!-- <ol class="carousel-indicators">
      <li data-target="#carousel-example-1z" data-slide-to="0" class="active"></li>
      <li data-target="#carousel-example-1z" data-slide-to="1"></li>
      <li data-target="#carousel-example-1z" data-slide-to="2"></li>
    </ol> -->
    <!--/.Indicators-->

    <!--Slides-->
    <div class="carousel-inner" role="listbox">

      <!--First slide-->
      <div class="carousel-item active">
        <div class="view" style="background-image: url('https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/8-col/img%282%29.jpg'); background-repeat: no-repeat; background-size: cover;">

          <!-- Mask & flexbox options-->
          <div class="mask rgba-black-strong d-flex justify-content-center align-items-center">

            <!-- Content -->
            <div class="text-center white-text mx-5 wow fadeIn">
              <h1 class="mb-4">
                <i class="fas fa-sun"></i>
                <strong>Solstyce Closet</strong>
              </h1>

              <p>
                <strong>Get the best goods here!</strong>
              </p>

              <p class="mb-4 d-none d-md-block">
                <strong>We have it all for you!</strong>
              </p>

            <!--   <a target="_blank" href="https://mdbootstrap.com/education/bootstrap/" class="btn btn-outline-white btn-lg">Start
                free tutorial
                <i class="fas fa-graduation-cap ml-2"></i>
              </a> -->
            </div>
            <!-- Content -->

          </div>
          <!-- Mask & flexbox options-->

        </div>
      </div>
      <!--/First slide-->
   </div>
    <!--/.Slides-->

    <!--Controls-->
    <!-- <a class="carousel-control-prev" href="#carousel-example-1z" role="button" data-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="carousel-control-next" href="#carousel-example-1z" role="button" data-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="sr-only">Next</span>
    </a> -->
    <!--/.Controls-->

  </div>
  <br>
  <!--/.Carousel Wrapper-->
      <!--Section: Products v.3-->
      <section class="text-center mb-4">

        <div class="row wow fadeIn">
          {% for item in object_list %}
          <div class="col-lg-3 col-md-6 mb-4">

            <!--Card-->
            <div class="card">

              <!--Card image-->
              <div class="view overlay">
                <!-- <img src="https://mdbootstrap.com/img/Photos/Horizontal/E-commerce/Vertical/12.jpg" class="card-img-top" -->
                <img src="{{ item.image.url }}"class="card-img-top" > 
                
                <a href="{{ item.get_absolute_url }}">
                  <div class="mask rgba-white-slight"></div>
                </a>
              </div>
              <!--Card image-->

              <!--Card content-->
              <div class="card-body text-center">
                <!--Category & Title-->
                <a href="" class="grey-text">
                  <h5>{{ item.get_category_display }}</h5>
                </a>
                <h5>
                  <strong>
                    <a href="{{ item.get_absolute_url }}" class="dark-grey-text">{{ item.title }}
                      {% if item.label == 'p' %}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">HOT</span>
                      {% elif item.label == 's' %}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">Top Seller!</span>
                      {% else %}
                      <span class="badge badge-pill {{ item.get_label_display }}-color">NEW</span>
                      {% endif %}
                    </a>
                  </strong>
                </h5>

                <h4 class="font-weight-bold blue-text">
                  <strong>$
                    {% if item.discount_price %}
                    {{ item.discount_price }}
                    {% else %}
                    {{ item.price }}
                    {% endif %}
                  </strong>
                </h4>

              </div>
              <!--Card content-->

            </div>
            <!--Card-->

          </div>
          {% endfor %}
        </div>
      </section>
      <!--Section: Products v.3-->

      <!--Pagination-->
      {% if is_paginated %}
      <nav class="d-flex justify-content-center wow fadeIn">
        <ul class="pagination pg-blue">

          <!--Arrow left-->
          {% if page_obj.has_previous %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.previous_page_number }}" aria-label="Previous">
              <span aria-hidden="true">&laquo;</span>
              <span class="sr-only">Previous</span>
            </a>
          </li>
          {% endif %}
          <li class="page-item active">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}">{{ page_obj.number }}
              <span class="sr-only">(current)</span>
            </a>
          </li>
         {% if page_obj.has_next %}
          <li class="page-item">
            <a class="page-link" href="?page={{ page_obj.next_page_number }}" aria-label="Next">
              <span aria-hidden="true">&raquo;</span>
              <span class="sr-only">Next</span>
            </a>
          </li>
          {% endif %}
        </ul>
      </nav>
      <!--Pagination-->
      {% endif %}

    </div>
  </main>
  <!--Main layout-->
{% endblock content %}